brew 'ant'
brew 'apache-spark'
brew 'awscli'
brew 'bash-completion'
brew 'Caskroom/cask/xquartz'  # for R
brew 'colordiff'
brew 'coreutils'
brew 'ctags'
brew 'elasticsearch'
brew 'elixir'
brew 'ffmpeg'
brew 'gawk'
brew 'gcc'
brew 'geoip'
brew 'git'
brew 'gpg'
brew 'graphicsmagick'
brew 'hadoop'
brew 'imagemagick'
brew 'jq'
brew 'leiningen'
brew 'llvm'
brew 'lua'
brew 'markdown'
brew 'maven'
brew 'memcached'
brew 'mongo'
brew 'mysql'
brew 'node'
brew 'percona-toolkit'
brew 'pidof'
brew 'postgresql'
brew 'protobuf'
brew 'python'
brew 'python3'
brew 'r'
brew 're2c'
brew 'redis'
brew 'rust'
brew 'sbt'
brew 'scala'
# NOTE: need 2.0.9 + libstemmer sha hack + https://github.com/mistydemeo/homebrew/commit/294368a97817001721d23b3e36b251f5f09e05a4
#brew 'sphinx', args: '--mysql'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tree'
brew 'unrar'
brew 'v8'
brew 'watch'
brew 'zeromq'

tap 'homebrew/science'
#brew 'opencv'  # requires "pip install numpy"

tap 'homebrew/completions'
brew 'bundler-completion'
brew 'cargo-completion'
brew 'gem-completion'
brew 'maven-completion'
brew 'pip-completion'
brew 'rails-completion'
brew 'rake-completion'
brew 'ruby-completion'
brew 'rustc-completion'
