brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'gawk'
brew 'gcc'
brew 'ghostscript'
brew 'git'
brew 'git-delta'
brew 'gpg'
brew 'hub'
brew 'imagemagick'
brew 'jq'
brew 'llvm'
brew 'lua'
brew 'pidof'
brew 'postgresql'
brew 'pstree'
brew 'pv'
brew 'python'
brew 'python3'
brew 'redis'
brew 'sbt'
brew 'scala'
brew 'source-highlight'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tree'
brew 'watch'

# Bash completion
brew 'bundler-completion'
brew 'gem-completion'
brew 'pip-completion'
brew 'rails-completion'
brew 'rake-completion'
brew 'ruby-completion'

